version: '3.8'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.9
    ports:
      - '16686:16686'
      - '14250:14250'
      - '6831:6831/udp'

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:8080'
    ports:
      - '9092:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db:
    driver: local
  prometheus_data:
    driver: local